### ISSUE TITLE
Improve fault tolerance for abandoned closing tag

### ISSUE THREAD

**Issue by vinayhk1989** [SAP/xml-tools#268]
For below xml code snippet
```xml
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
    <edmx:Reference Uri="some/uri">
        <edmx:Include Namespace="com.sap.vocabularies.UI.v1" Alias="UI" />
    </edmx:Reference>
    <edmx:Reference Uri="/here/goes/your/serviceurl/$metadata">
        <edmx:Include Namespace="ns-demo" Alias="demo" />
    </edmx:Reference>
    <edmx:DataServices>
        <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="local">
            <Annotations Target="demo.demoTarget">
 		<Annotation Term="UI.LineItem" >
                    <Collection>
                        <Record Type="UI.DataField">
                            <PropertyValue Property="Value" Path="MainProductCategory"/>
                        </Record>
                        </Record> `|`
                    </Collection>
                </Annotation> 											
            </Annotations>
        </Schema>
    </edmx:DataServices>
</edmx:Edmx>
```
where `|` represents the cursor position, there exits two issues.
* XML-Tools reports diagnostic on the wrong element. Here `edxm:Edmx`. The diagnostic should be reported close to the element where there is an issue
* AST seems to be wrong. Generated AST points to the wrong parent. For the above cursor position, parent should be `Collection`, but it is Annotations

**Comment by bd82** [comment]
I am uncertain a good solution could be provided in this case.

- We have a redundant closing tag ` </Record>`
- As humans we can **guess** that this closing tag is redundant because of its:
  1. tag name same as the closing tag above.
  2. tag name does not match the `parent` 
  2. indentation same as the closing tag above.

However translating these heuristics to **automated** error recovery logic is **problematic**.
Basically we **cannot be certain** as the point of making the decision if there is an error or not, e.g:
- Perhaps the `</Record>` is not in fact syntactically redundant and is required to **match** some element start.
- In other words perhaps, **only the name value** in the closing tag is incorrect, not the of the whole closing tag.

This means that in order to make the decision a closing tag is redundant or not we must **look/parse ahead** until the **end of the file** to see if the open/close tags are still aligned if we ignore that "potentially redundant tag".

Conceptually this will cause **exponential** performance issues because **every single time**, our new heuristic need be considered we would be creating a branch in our parsing which would require **parsing until the end** (in **both** branches).

For example JetBrains IDE has the same "issues" with the redundant closing tag messing up the XML parents hierarchy (see by the automatic formatting).

![image](https://user-images.githubusercontent.com/4233843/103479031-4706d380-4dd3-11eb-9141-d2b72d27200e.png)

**Comment by bd82** [comment]
I think the best way to approach this issue would be to implement the start/close tag name match validation.
- https://github.com/SAP/xml-tools/issues/14

For example in the above image you can see the many squiggly red lines with errors that say:
![image](https://user-images.githubusercontent.com/4233843/103479082-c1cfee80-4dd3-11eb-8fef-f232bab979bb.png)

While this does not solve the issue of fault tolerance, it does highlight to the end user that there is a problem with their
XML that need to be resolved.

**Comment by bd82** [comment]
I will be closing this issue for now.
#14 is not currently scheduled for development, but PR contributions are always most welcome 😄
