### ISSUE TITLE
Consider only using start/end offset in the APIs/Internal data structures

### ISSUE THREAD

**Issue by bd82** [SAP/xml-tools#33]
Is there any purpose to the added complexity of keeping line/column information?

**Comment by TwitchBronBron** [comment]
Editors like vscode use `Range` objects that represent start and end line and column information.

**Comment by bd82** [comment]
Hi @TwitchBronBron 

> Editors like vscode use Range objects that represent start and end line and column information.

That is true in VSCode's case @TwitchBronBron however I am unsure if that is true for other editors as well.

Regardless even when working with VSCode the line/column information in the AST (output from the Parser)
is not used because it may differ, e.g:
- line/columns starting at 0 or 1?
- The definition of line/columns depends on the definition of the line terminators.

So we are already using offsets in our communication with VSCode/LSP apis.
As offsets are the most low level and unambiguous api, e.g:
- https://github.com/SAP/xml-tools/blob/826d4c63516bfd6496d078365d54b826229082e9/packages/language-server/lib/language-services.js#L32-L36

**Comment by TwitchBronBron** [comment]
I use this parser in a transpiler that I maintain, and we print out line/column numbers for errors found in the XML. If xml-tools only had offsets, I'd have to map those offsets back to line and column information. Unless I'm missing something, this means I'd have to walk through the source file myself in order to convert the offsets to line/column information. That would result in `two` walks through the source file (xml-tools for parsing, and me for offset-remapping. Definitely not ideal. 

While I understand there may be ambiguity between line/column starting at 0/1, it's easy enough to document, and pushing line/column resolution back consumers of this package would be a downgrade to `xml-tools`, in my opinion.

**Comment by bd82** [comment]
Hi @TwitchBronBron 

I may have been too focused on our specific use case for this library (Language Servers which are currently only used in VSCode).
In a wider consumption scope it does make sense to keep line/column information.
